# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Instalar dependências do projeto
- script: |
    npm ci
  displayName: 'Install dependencies'

# Instalar navegadores do Playwright
- script: |
    npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

# Rodar os testes Playwright
- script: |
    npx playwright test
  displayName: 'Run Playwright tests'

# Publicar o relatório como artefato
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'playwright-report'
    ArtifactName: 'playwright-report'
    publishLocation: 'Container'
  condition: succeededOrFailed()
  displayName: 'Publish Playwright Report'
